analyzer:
  errors:
    always_put_required_named_parameters_first: ignore
    avoid_catches_without_on_clauses: ignore
    avoid_dynamic_calls: ignore
    avoid_positional_boolean_parameters: ignore
    avoid_print: ignore
    constant_identifier_names: ignore
    deprecated_member_use: ignore
    discarded_futures: ignore
    inference_failure_on_function_invocation: ignore
    inference_failure_on_instance_creation: ignore
    invalid_annotation_target: ignore
    lines_longer_than_80_chars: ignore
    one_member_abstracts: ignore
    recursive_getters: ignore
    strict_raw_type: ignore
    unnecessary_statements: ignore
    unreachable_switch_case: ignore
    use_setters_to_change_properties: ignore
include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false